In [4]:
1/(0.9+0.05)

1.0526315789473684

In [3]:
0.9**2 *10


8.100000000000001

In [9]:
N=int(input())
a=[]
for i in range(N):
    a.append(list(map(int, input().split())))

3
1 2 3
1 2 3
1 2 2


In [11]:
a

[[1, 2, 3], [1, 2, 3], [1, 2, 2]]

In [13]:
N=int(input())
a=[]
for i in range(N):
    a.append(list(map(int, input().split())))
b=[]
for i in range(N):
    for j in range(N):
        if i==j:
            b.append(a[i][j])
print(b)

3
1 2 3
4 5 6
7 8 9


[1, 5, 9]

In [14]:
print(b)

[1, 5, 9]


Дана матрица [N×M]. Необходимо вывести через пробел номер строки и номер столбца минимального значения матрицы, если одинаковых значений несколько, то вывести с наименьшим номером строки. Если и в этом случае остались одинаковые значения, то вывести с наименьшим номером столбца.

Значения матрицы - целые числа на отрезке [-100; 100], N,M - целые числа на отрезке [1; 100].

На вход будет подано: на первой строке задается количество строк матрицы N и через пробел количество столбцов матрицы M. На последующих N строках задаются строки матрицы, каждая из которых содержит M целых чисел, разделенных пробелом

In [65]:
import numpy as np
N,M=map(int, input().split())
a=[]
for i in range(N):
    a.append(list(map(int, input().split())))
a=np.array(a)
result = np.where(a == np.amin(a))
listOfCordinates = list(zip(result[0]+1, result[1]+1))
if len(listOfCordinates)>1:
    print(min(listOfCordinates))
else:
    print(listOfCordinates)

3 2
1 2
3 4
5 6
[(1, 1)]


Даны две матрицы порядка [N×M] и [M×L]. Необходимо вывести матрицу результат их перемножения. Значения матрицы - целые числа на отрезке [-100; 100]. N, M, L - целые числа на отрезке [1; 100].

На вход будет подано: на первой строке будет задано количество строк матрицы N и через пробел количество столбцов матрицы M. На последующих N строках задаются строки матрицы, каждая из которых содержит M целых чисел, разделенных пробелом. На N+2 строке задается количество строк матрицы M и через пробел количество столбцов матрицы L. На последующих M строках задаются строки матрицы, каждая из которых содержит L целых чисел, разделенных пробелом.

In [66]:
3 2
1 2
3 4
5 6
2 3
1 3 5
2 4 6

SyntaxError: invalid syntax (<ipython-input-66-da9308558a57>, line 1)

In [68]:
import numpy as np
N,M=map(int, input().split())
a=[]
for i in range(N):
    a.append(list(map(int, input().split())))
a=np.array(a)
M,L=map(int, input().split())
b=[]
for i in range(M):
    b.append(list(map(int, input().split())))
b=np.array(b)
print(res)

3 2
1 2
3 4
5 6
2 3
1 3 5
2 4 6


In [69]:
a,b

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 3, 5],
        [2, 4, 6]]))

In [70]:
res = np.dot(a,b) 

In [72]:
print(res)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


In [73]:
field_ = [input().split() for i in range(10)]

_ _ _ _ _ _ _ _ x _
_ _ _ x x * * _ x *
_ _ _ * _ _ _ _ x _
x _ _ _ _ _ _ _ * _
x _ _ _ _ _ _ _ _ x
_ _ _ x _ * _ _ _ x
_ _ * _ _ _ x _ _ x
_ _ _ x x _ x _ _ x
_ x _ _ _ _ x _ _ _
_ _ _ x _ _ _ _ x _


In [78]:
field_=np.array(field_)
if np.count_nonzero(field_ =='x')==20:
    print(1)
else:
    print(0)

20


In [ ]:
_ _ _ _ _ _ _ _ x _
_ _ _ x x * * _ x *
_ _ _ * _ _ _ _ x _
x _ _ _ _ _ _ _ * _
x _ _ _ _ _ _ _ _ x
_ _ _ x _ * _ _ _ x
_ _ * _ _ _ x _ _ x
_ _ _ x x _ x _ _ x
_ x _ _ _ _ x _ _ _
_ _ _ x _ _ _ _ x _

-------------------