In [47]:
import pandas as pd
import numpy as np
import matplotlib
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import Normalizer
from sklearn import preprocessing
from scipy import stats
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import StandardScaler
import matplotlib.patches as patches
from sklearn.metrics import roc_curve,auc
from scipy import interp
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, datasets
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import LeavePOut
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import StratifiedKFold

In [48]:
path = '/Users/dariapetrukhina/Desktop/data_science/MADE/ml/A'
names = range(1,31)
df_train = pd.read_csv(path + '/'+'train.csv', names=names)
df_train = df_train.add_prefix('feature_')

In [49]:
names = range(1,31)
df_test = pd.read_csv(path + '/'+'test.csv', names=names)
df_test = df_test.add_prefix('feature_')

In [50]:
df_test

feature_1   feature_2   feature_3   feature_4  feature_5   feature_6  \
0     394.650101 -102.778703  -48.854416   17.463193   4.744214  -90.504260   
1      62.200701 -139.323500  235.644493   10.860594   1.921110   39.088440   
2     232.736729    5.502143  204.738165   45.738959   1.338264   33.604743   
3     340.045437 -129.924115   62.694027   61.899097  -1.294288  -58.616589   
4     -60.576957   71.958472  489.203093  121.380719  -3.620431   44.666983   
...          ...         ...         ...         ...        ...         ...   
1995 -471.546548   10.111993   26.954527   15.095227  -3.063143  103.709142   
1996  338.582687  -66.286491   85.950052   62.767924  -9.850459  -28.715758   
1997 -606.008941   62.500403  105.618597  -72.866870   8.377977   90.363769   
1998 -177.330776  -49.753695  113.362911   81.025957  -3.930623   49.207840   
1999 -836.655138  -80.742934  169.299357   22.026026  -6.558834  134.088064   

       feature_7   feature_8   feature_9  feature_10  ...  feature_21  \
0     135.111157  -27.691507  192.961067    1.755201  ...  -56.947165   
1    -186.024836  -53.158605 -122.290561    1.426944  ...  -45.854744   
2      92.235943 -115.127927  -95.263085    2.048801  ...  -15.638165   
3     -55.080664   10.115134    9.051856    2.732693  ...   13.407883   
4    -161.487192  137.920737  540.680255    1.172919  ...  -51.559846   
...          ...         ...         ...         ...  ...         ...   
1995  154.251641   52.139437  -18.130711    1.275376  ...  -22.700361   
1996  -18.165461   22.083233  -20.414047    0.171980  ...  -53.432832   
1997  122.605637 -132.766117  196.318687    2.103777  ...  -33.583933   
1998   75.985199  124.601644  155.490571    0.840811  ...  -64.400056   
1999  152.312695   72.208317 -154.817199    0.835230  ...  -80.170539   

      feature_22  feature_23  feature_24  feature_25  feature_26  feature_27  \
0     140.952506    1.885744   11.483086 -131.665132   12.876561    0.156747   
1    -148.360929    2.614495  -24.895114  -40.050598    7.376349    1.962719   
2    -234.606490    0.409558  286.011182   48.109151   -9.277772    1.838195   
3     -56.332212    2.801811   70.875892   26.673509    2.389621    2.188665   
4      -6.645415    1.889414  -21.814728  -91.701674   -9.206418    1.211916   
...          ...         ...         ...         ...         ...         ...   
1995  321.521536    1.802898   37.775150    1.023489    5.859330    2.494973   
1996 -106.773383    1.421168   -4.654932  -28.263999   -1.993743    1.670567   
1997  474.485779    1.961537  -10.633976   18.384643    0.436849    2.203840   
1998  171.401230    0.247412  157.263552    1.933496   12.835083    1.749624   
1999  363.929003    2.526689  -15.294976  -72.794742    8.620293    1.710575   

      feature_28  feature_29  feature_30  
0    -185.849095  -29.314711  -84.254441  
1    -123.776910   65.756136  -10.378203  
2      19.461847  126.144518 -121.300353  
3     109.700845  109.378365  -58.425305  
4     -11.602746   -8.162451  -87.902970  
...          ...         ...         ...  
1995  -14.614198  -86.615411   12.791456  
1996  -33.261460  159.403484  -23.817695  
1997  103.288596   -8.135033   21.901938  
1998   50.869380  -60.932621  -64.972888  
1999  -49.201199 -124.800089  -13.015749  

[2000 rows x 30 columns]

In [51]:
df_train_target = pd.read_csv(path +'/'+'train-target.csv', names ='-')
df_train_target.columns = ['result']

In [52]:
names = range(1,31)
df_test = pd.read_csv(path + '/'+'test.csv', names=names)

In [53]:
columns_names = list(df_train.columns)
columns_names

['feature_1',
 'feature_2',
 'feature_3',
 'feature_4',
 'feature_5',
 'feature_6',
 'feature_7',
 'feature_8',
 'feature_9',
 'feature_10',
 'feature_11',
 'feature_12',
 'feature_13',
 'feature_14',
 'feature_15',
 'feature_16',
 'feature_17',
 'feature_18',
 'feature_19',
 'feature_20',
 'feature_21',
 'feature_22',
 'feature_23',
 'feature_24',
 'feature_25',
 'feature_26',
 'feature_27',
 'feature_28',
 'feature_29',
 'feature_30']

In [54]:
updated_features = columns_names
updated_features.remove('feature_18')
updated_features.remove('feature_23')
updated_features.remove('feature_8')

In [55]:
X_test = df_test

In [56]:
updated_features

['feature_1',
 'feature_2',
 'feature_3',
 'feature_4',
 'feature_5',
 'feature_6',
 'feature_7',
 'feature_9',
 'feature_10',
 'feature_11',
 'feature_12',
 'feature_13',
 'feature_14',
 'feature_15',
 'feature_16',
 'feature_17',
 'feature_19',
 'feature_20',
 'feature_21',
 'feature_22',
 'feature_24',
 'feature_25',
 'feature_26',
 'feature_27',
 'feature_28',
 'feature_29',
 'feature_30']

In [57]:
# train data
scaler = MinMaxScaler(feature_range=(0, 100), copy=False)

columns_normalize = list(df_train.columns)

for column in columns_normalize:
    scaler.fit(np.array(df_train[column]).reshape(-1, 1))
    scaled = scaler.transform(np.array(df_train[column]).reshape(-1, 1))
    df_train[column] = pd.Series(np.reshape(scaled, newshape=scaled.shape[0]))

In [58]:
# test data
scaler = MinMaxScaler(feature_range=(0, 100), copy=False)

columns_normalize = list(df_test.columns)

for column in columns_normalize:
    scaler.fit(np.array(df_test[column]).reshape(-1, 1))
    scaled = scaler.transform(np.array(df_test[column]).reshape(-1, 1))
    df_test[column] = pd.Series(np.reshape(scaled, newshape=scaled.shape[0]))

In [59]:
X_train = df_train.loc[:, updated_features]

In [60]:
Y_train = df_train_target

In [61]:
X_train

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0     41.653022  33.956958  54.207405  51.959344  35.675955  60.404985   
1     47.939845  43.728723  37.945892  43.649167  73.033504  47.941740   
2     51.936436  66.111787  38.791462  23.333607  40.222082  39.720234   
3     59.152893  46.910975  25.441260  53.419098  40.617787  38.187370   
4     45.240374  31.593614  40.998563  42.508066  56.924954  46.249625   
...         ...        ...        ...        ...        ...        ...   
9995  45.470490  60.257020  39.614698  62.843584  33.796599  45.792811   
9996  41.310408  35.431016  49.157084  49.434145  32.311947  58.658944   
9997  42.782169  33.362351  30.810351  32.255422  39.520370  37.452780   
9998  40.235078  53.461886  33.938616  56.209521  64.565753  61.343814   
9999  25.467608  23.529875  47.855677  22.590551  35.011944  64.960988   

      feature_7  feature_9  feature_10  feature_11  ...  feature_20  \
0     44.162117  43.084082   97.980535   63.691908  ...   42.129531   
1     41.517757  49.246912   95.195417   41.355604  ...   49.655801   
2     47.605261  42.669018    5.297993   59.010559  ...   36.038615   
3     65.779667  37.103070    2.926504   34.169192  ...   60.838478   
4     53.605173  42.329909   96.717116   40.218348  ...   50.671092   
...         ...        ...         ...         ...  ...         ...   
9995  74.587045  55.723596   97.512351   42.245825  ...   56.844529   
9996  37.596024  47.499229    5.196654   53.786437  ...   35.563101   
9997  42.955510  64.984206    0.875804   35.002432  ...   73.224089   
9998  54.967420  39.191046   99.256010   23.328086  ...   53.209722   
9999  65.376506  44.303546   97.197095   58.994412  ...   22.427034   

      feature_21  feature_22  feature_24  feature_25  feature_26  feature_27  \
0      55.021019   56.152311   32.469113   53.116589   55.105401   63.332429   
1      65.358236   61.317796   67.785518   63.451863   41.709333   18.720869   
2      51.896843   59.079263   43.502127   71.255261   61.540843   45.472662   
3      71.521479   41.434006   70.782896   54.721278   44.963588   47.280975   
4      58.823128   67.388282   45.184256   61.850336   52.791324   49.113770   
...          ...         ...         ...         ...         ...         ...   
9995   58.163205   81.840251   52.443222   54.712818   51.255620   40.741742   
9996   72.901113   50.867491   67.951938   41.603875   42.877317   46.409350   
9997   44.644806   60.006937   46.898220   43.470823   51.279665   48.203090   
9998   32.717943   56.004157   59.365336   58.482221   51.784362   63.394160   
9999   58.969160   57.853804   58.580146   26.950710   29.202446   37.487617   

      feature_28  feature_29  feature_30  
0      52.756573   41.480057   54.859711  
1      43.655978   39.784284   49.169690  
2      33.014883   33.199135   36.047875  
3      44.516702   60.391391   47.396172  
4      31.055531   46.389329   47.554782  
...          ...         ...         ...  
9995   60.223419   36.105511   30.358777  
9996   52.098422   38.100921   50.731005  
9997   40.722310   21.382207   62.585151  
9998   46.678081   46.286695   61.422496  
9999   66.782780   37.813320   58.186069  

[10000 rows x 27 columns]

In [17]:
df_test

1          2          3          4          5          6   \
0     67.196026  29.948441  37.247107  52.226648  66.520890  31.526988   
1     54.593970  23.731831  60.917251  50.991850  61.151851  50.510761   
2     61.058426  48.368022  58.345863  57.514697  60.043381  49.707466   
3     65.126144  25.330754  46.527873  60.536918  55.036739  36.198149   
4     49.939875  59.672863  82.013180  71.660993  50.612829  51.327951   
...         ...        ...        ...        ...        ...        ...   
1995  34.361378  49.152201  43.554367  51.783798  51.672691  59.976917   
1996  65.070696  36.156107  48.462761  60.699403  38.764428  40.578261   
1997  29.264354  58.063958  50.099172  35.333390  73.431660  58.021981   
1998  45.514124  38.968489  50.743495  64.113966  50.022899  51.993132   
1999  20.521320  33.696931  55.397375  53.079975  45.024512  64.427064   

             7          8          9          10  ...         21         22  \
0     57.126212  55.646889  60.960745  58.442486  ...  25.515487  60.795510   
1     20.128811  52.939726  29.882536  47.482577  ...  29.146593  36.059032   
2     52.186649  46.352362  32.546965  68.245254  ...  39.037998  28.684984   
3     35.214613  59.665751  42.830565  91.079149  ...  48.546229  43.927545   
4     22.955741  73.251540  95.239678  39.001159  ...  27.279027  48.175797   
...         ...        ...        ...        ...  ...        ...        ...   
1995  59.331346  64.132952  40.150846  42.422004  ...  36.726187  76.234274   
1996  39.467535  60.937965  39.925750   5.581623  ...  26.665904  39.614793   
1997  55.685477  44.477415  61.291747  70.080789  ...  33.163446  89.312812   
1998  50.314435  71.835715  57.266820  27.912691  ...  23.075781  63.398895   
1999  59.107965  66.266282  26.675987  27.726359  ...  17.913310  79.860139   

             23          24         25         26         27         28  \
0     62.868997   50.175400  19.795648  67.290895   5.167378  19.584270   
1     87.167156   43.573055  36.869419  57.745417  65.440651  29.026753   
2     13.649692  100.000000  53.299338  28.842612  61.284747  50.816375   
3     93.412688   60.954708  49.304478  49.091077  72.981465  64.543621   
4     62.991363   44.132120  27.243450  28.966444  40.383058  46.090798   
...         ...         ...        ...        ...        ...        ...   
1995  60.106740   54.947194  44.524204  55.112668  83.204331  45.632693   
1996  47.379007   47.246482  39.066032  41.483860  55.690270  42.796053   
1997  65.396115   46.161335  47.759721  45.702090  73.487935  63.568183   
1998   8.243389   76.633360  44.693798  67.218911  58.328750  55.594120   
1999  84.239509   45.315401  30.767046  59.904250  57.025517  40.371284   

             29         30  
0     45.215599  32.445331  
1     57.127656  46.406354  
2     64.694117  25.444449  
3     62.593375  37.326483  
4     47.865906  31.755837  
...         ...        ...  
1995  38.036015  50.784921  
1996  68.861354  43.866578  
1997  47.869342  52.506607  
1998  41.253982  36.089130  
1999  33.251603  45.907914  

[2000 rows x 30 columns]

In [62]:
df_test = df_test.add_prefix('feature_')

In [63]:
df_test

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0     67.196026  29.948441  37.247107  52.226648  66.520890  31.526988   
1     54.593970  23.731831  60.917251  50.991850  61.151851  50.510761   
2     61.058426  48.368022  58.345863  57.514697  60.043381  49.707466   
3     65.126144  25.330754  46.527873  60.536918  55.036739  36.198149   
4     49.939875  59.672863  82.013180  71.660993  50.612829  51.327951   
...         ...        ...        ...        ...        ...        ...   
1995  34.361378  49.152201  43.554367  51.783798  51.672691  59.976917   
1996  65.070696  36.156107  48.462761  60.699403  38.764428  40.578261   
1997  29.264354  58.063958  50.099172  35.333390  73.431660  58.021981   
1998  45.514124  38.968489  50.743495  64.113966  50.022899  51.993132   
1999  20.521320  33.696931  55.397375  53.079975  45.024512  64.427064   

      feature_7  feature_8  feature_9  feature_10  ...  feature_21  \
0     57.126212  55.646889  60.960745   58.442486  ...   25.515487   
1     20.128811  52.939726  29.882536   47.482577  ...   29.146593   
2     52.186649  46.352362  32.546965   68.245254  ...   39.037998   
3     35.214613  59.665751  42.830565   91.079149  ...   48.546229   
4     22.955741  73.251540  95.239678   39.001159  ...   27.279027   
...         ...        ...        ...         ...  ...         ...   
1995  59.331346  64.132952  40.150846   42.422004  ...   36.726187   
1996  39.467535  60.937965  39.925750    5.581623  ...   26.665904   
1997  55.685477  44.477415  61.291747   70.080789  ...   33.163446   
1998  50.314435  71.835715  57.266820   27.912691  ...   23.075781   
1999  59.107965  66.266282  26.675987   27.726359  ...   17.913310   

      feature_22  feature_23  feature_24  feature_25  feature_26  feature_27  \
0      60.795510   62.868997   50.175400   19.795648   67.290895    5.167378   
1      36.059032   87.167156   43.573055   36.869419   57.745417   65.440651   
2      28.684984   13.649692  100.000000   53.299338   28.842612   61.284747   
3      43.927545   93.412688   60.954708   49.304478   49.091077   72.981465   
4      48.175797   62.991363   44.132120   27.243450   28.966444   40.383058   
...          ...         ...         ...         ...         ...         ...   
1995   76.234274   60.106740   54.947194   44.524204   55.112668   83.204331   
1996   39.614793   47.379007   47.246482   39.066032   41.483860   55.690270   
1997   89.312812   65.396115   46.161335   47.759721   45.702090   73.487935   
1998   63.398895    8.243389   76.633360   44.693798   67.218911   58.328750   
1999   79.860139   84.239509   45.315401   30.767046   59.904250   57.025517   

      feature_28  feature_29  feature_30  
0      19.584270   45.215599   32.445331  
1      29.026753   57.127656   46.406354  
2      50.816375   64.694117   25.444449  
3      64.543621   62.593375   37.326483  
4      46.090798   47.865906   31.755837  
...          ...         ...         ...  
1995   45.632693   38.036015   50.784921  
1996   42.796053   68.861354   43.866578  
1997   63.568183   47.869342   52.506607  
1998   55.594120   41.253982   36.089130  
1999   40.371284   33.251603   45.907914  

[2000 rows x 30 columns]

In [64]:
X_test = df_test.loc[:, updated_features]

In [65]:
Y_train.columns.name = None

In [66]:
Y_train = np.ravel(Y_train,order='C')

In [67]:
Y_train

array([1, 1, 0, ..., 0, 1, 1])

### Log Regression

In [68]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression

In [69]:
kfold = model_selection.KFold(n_splits=10, shuffle=True,random_state=7 )
model = LogisticRegression(max_iter=10000)
scoring = 'roc_auc'
results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
print(("AUC: %.3f (%.3f)") % (results.mean(), results.std()))

AUC: 1.000 (0.000)


In [70]:
kfold = model_selection.KFold(n_splits=10)
model = LogisticRegression(max_iter=1000)
scoring = 'roc_auc'
results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
print(("AUC: %.3f (%.3f)") % (results.mean(), results.std()))

AUC: 1.000 (0.000)


### SVM

In [71]:
from sklearn.model_selection import cross_val_score
from sklearn import svm

clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, X_train, Y_train, cv=5)
scores

array([1., 1., 1., 1., 1.])

In [72]:
from sklearn.pipeline import make_pipeline

clf = make_pipeline(preprocessing.StandardScaler(), svm.SVC(C=1))
cross_val_score(clf, X_train, Y_train, cv=5)

array([1., 1., 1., 1., 1.])

In [73]:
from sklearn.model_selection import ShuffleSplit
n_samples = X_train.shape[0]
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
cross_val_score(clf, X_train, Y_train, cv=5)

array([1., 1., 1., 1., 1.])

## Solution 1 (Log Regression)

In [144]:
model.fit(X_train,Y_train)
pred2 = model.predict_proba(X_test)[:, 1]

In [145]:
pred2

array([0.83760879, 0.08613495, 0.97422558, ..., 0.90565736, 0.00824209,
       0.00391782])

In [148]:
solution = pd.DataFrame(pred2)
solution

0
0     0.837609
1     0.086135
2     0.974226
3     0.999646
4     0.235150
...        ...
1995  0.173141
1996  0.000120
1997  0.905657
1998  0.008242
1999  0.003918

[2000 rows x 1 columns]

In [152]:
solution2 = pd.DataFrame(pred2, columns = ['0.837609'])
solution2 = solution2.iloc[1:]


In [153]:
solution2

0.837609
1     0.086135
2     0.974226
3     0.999646
4     0.235150
5     0.000653
...        ...
1995  0.173141
1996  0.000120
1997  0.905657
1998  0.008242
1999  0.003918

[1999 rows x 1 columns]

In [157]:
solution2.to_csv('A_solution4.csv', index=False)

In [158]:
path = '/Users/dariapetrukhina/Desktop/data_science/MADE/ml/A'
check_sol = pd.read_csv(path + '/'+'A_solution4.csv')

In [159]:
check_sol

0.837609
0     0.086135
1     0.974226
2     0.999646
3     0.235150
4     0.000653
...        ...
1994  0.173141
1995  0.000120
1996  0.905657
1997  0.008242
1998  0.003918

[1999 rows x 1 columns]

## Solution 2

In [79]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import SVC, LinearSVC

model_svc = LinearSVC(max_iter = 100000)
model = CalibratedClassifierCV(model_svc) 
model.fit(X_train, Y_train)

CalibratedClassifierCV(base_estimator=LinearSVC(C=1.0, class_weight=None,
                                                dual=True, fit_intercept=True,
                                                intercept_scaling=1,
                                                loss='squared_hinge',
                                                max_iter=100000,
                                                multi_class='ovr', penalty='l2',
                                                random_state=None, tol=0.0001,
                                                verbose=0),
                       cv=None, method='sigmoid')

In [80]:
pred3 = model.predict_proba(X_test)[:, 1]

In [81]:
pred3

array([0.89582673, 0.48169971, 0.90668703, ..., 0.91747036, 0.03129585,
       0.04856211])

In [82]:
solution3 = pd.DataFrame(pred3, columns = ['0.89582673'])
solution3 = solution3.iloc[1:]

In [85]:
solution3.to_csv('A_solution5.csv', index=False)

In [86]:
solution3

0.89582673
1       0.481700
2       0.906687
3       0.996290
4       0.197016
5       0.002634
...          ...
1995    0.269998
1996    0.001855
1997    0.917470
1998    0.031296
1999    0.048562

[1999 rows x 1 columns]